# Generated by Django 2.0.6 on 2018-06-30 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codigo',
            old_name='username',
            new_name='codigo',
        ),
    ]
